/**
 * This file was automatically generated by tools/generators/generate-cache-file.js file
 */

import { cartsApi } from "./carts-endpoints"
import { productsApi } from "./products-endpoints"
import { todosApi } from "./todos-endpoints"
import { usersApi } from "./users-endpoints"

export const addTodosCacheKeys = () =>
  todosApi.enhanceEndpoints({
    endpoints: {
      getManyTodos: { providesTags: ["todos"] },
      createOneTodo: { invalidatesTags: ["todos"] },
      updateOneTodo: { invalidatesTags: ["todos"] },
      deleteOneTodo: { invalidatesTags: ["todos"] },
    },
  })

export const addProductsCacheKeys = () =>
  productsApi.enhanceEndpoints({
    endpoints: {
      getManyProducts: { providesTags: ["products"] },
      createOneProduct: { invalidatesTags: ["products"] },
      updateOneProduct: { invalidatesTags: ["products"] },
      deleteOneProduct: { invalidatesTags: ["products"] },
    },
  })

export const addCartCacheKeys = () =>
  cartsApi.enhanceEndpoints({
    endpoints: {
      getManyCarts: { providesTags: ["carts"] },
      createOneCart: { invalidatesTags: ["carts"] },
      addCartItem: { invalidatesTags: ["carts"] },
      updateOneCart: { invalidatesTags: ["carts"] },
      deleteOneCart: { invalidatesTags: ["carts"] },
      removeCartItem: { invalidatesTags: ["carts"] },
      getOneCart: { providesTags: ["cart"] },
      getCartItems: { providesTags: ["cart"] },
    },
  })

export const addUsersCacheKeys = () =>
  usersApi.enhanceEndpoints({
    endpoints: {
      getManyUsers: { providesTags: ["users"] },
      createOneUser: { invalidatesTags: ["users"] },
      updateOneUser: { invalidatesTags: ["users"] },
      deleteOneUser: { invalidatesTags: ["users"] },
    },
  })

export const addGeneratedCacheKeys = () => {
  addTodosCacheKeys()
  addProductsCacheKeys()
  addCartCacheKeys()
  addUsersCacheKeys()
}
